services:
  - type: web
    name: n8n-neomonk
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: WEBHOOK_URL
        value: https://n8n-neomonk.onrender.com/